<?php
/**
 * AppsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fn
 *
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AppsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appsAppDelete
     *
     * Delete an app..
     *
     */
    public function testAppsAppDelete()
    {
    }

    /**
     * Test case for appsAppGet
     *
     * Get information for a app..
     *
     */
    public function testAppsAppGet()
    {
    }

    /**
     * Test case for appsAppPatch
     *
     * Updates an app..
     *
     */
    public function testAppsAppPatch()
    {
    }

    /**
     * Test case for appsGet
     *
     * Get all app names..
     *
     */
    public function testAppsGet()
    {
    }

    /**
     * Test case for appsPost
     *
     * Post new app.
     *
     */
    public function testAppsPost()
    {
    }
}
