<?php
/**
 * CallApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fn
 *
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CallApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CallApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appsAppCallsCallGet
     *
     * Get call information.
     *
     */
    public function testAppsAppCallsCallGet()
    {
    }

    /**
     * Test case for appsAppCallsCallLogDelete
     *
     * Delete call log entry.
     *
     */
    public function testAppsAppCallsCallLogDelete()
    {
    }

    /**
     * Test case for appsAppCallsCallLogGet
     *
     * Get call logs.
     *
     */
    public function testAppsAppCallsCallLogGet()
    {
    }

    /**
     * Test case for appsAppCallsGet
     *
     * Get app-bound calls..
     *
     */
    public function testAppsAppCallsGet()
    {
    }
}
