<?php
/**
 * RoutesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fn
 *
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RoutesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoutesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appsAppRoutesGet
     *
     * Get route list by app name..
     *
     */
    public function testAppsAppRoutesGet()
    {
    }

    /**
     * Test case for appsAppRoutesPost
     *
     * Create new Route.
     *
     */
    public function testAppsAppRoutesPost()
    {
    }

    /**
     * Test case for appsAppRoutesRouteDelete
     *
     * Deletes the route.
     *
     */
    public function testAppsAppRoutesRouteDelete()
    {
    }

    /**
     * Test case for appsAppRoutesRouteGet
     *
     * Gets route by name.
     *
     */
    public function testAppsAppRoutesRouteGet()
    {
    }

    /**
     * Test case for appsAppRoutesRoutePatch
     *
     * Update a Route, Fails if the route or app does not exist. Accepts partial updates / skips validation of zero values..
     *
     */
    public function testAppsAppRoutesRoutePatch()
    {
    }

    /**
     * Test case for appsAppRoutesRoutePut
     *
     * Create a Route if it does not exist. Update if it does. Will also create app if it does not exist. Put does not skip validation of zero values.
     *
     */
    public function testAppsAppRoutesRoutePut()
    {
    }
}
