<?php
/**
 * RoutesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fn
 *
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\Configuration;
use \Swagger\Client\ObjectSerializer;

/**
 * RoutesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoutesApi
{
    /**
     * API Client
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Swagger\Client\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return RoutesApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation appsAppRoutesGet
     *
     * Get route list by app name.
     *
     * @param string $app Name of app for this set of routes. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\RoutesWrapper
     */
    public function appsAppRoutesGet($app)
    {
        list($response) = $this->appsAppRoutesGetWithHttpInfo($app);
        return $response;
    }

    /**
     * Operation appsAppRoutesGetWithHttpInfo
     *
     * Get route list by app name.
     *
     * @param string $app Name of app for this set of routes. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\RoutesWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function appsAppRoutesGetWithHttpInfo($app)
    {
        // verify the required parameter 'app' is set
        if ($app === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app when calling appsAppRoutesGet');
        }
        // parse inputs
        $resourcePath = "/apps/{app}/routes";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($app !== null) {
            $resourcePath = str_replace(
                "{" . "app" . "}",
                $this->apiClient->getSerializer()->toPathValue($app),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\RoutesWrapper',
                '/apps/{app}/routes'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\RoutesWrapper', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\RoutesWrapper', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation appsAppRoutesPost
     *
     * Create new Route
     *
     * @param string $app name of the app. (required)
     * @param \Swagger\Client\Model\RouteWrapper $body One route to post. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\RouteWrapper
     */
    public function appsAppRoutesPost($app, $body)
    {
        list($response) = $this->appsAppRoutesPostWithHttpInfo($app, $body);
        return $response;
    }

    /**
     * Operation appsAppRoutesPostWithHttpInfo
     *
     * Create new Route
     *
     * @param string $app name of the app. (required)
     * @param \Swagger\Client\Model\RouteWrapper $body One route to post. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\RouteWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function appsAppRoutesPostWithHttpInfo($app, $body)
    {
        // verify the required parameter 'app' is set
        if ($app === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app when calling appsAppRoutesPost');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling appsAppRoutesPost');
        }
        // parse inputs
        $resourcePath = "/apps/{app}/routes";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($app !== null) {
            $resourcePath = str_replace(
                "{" . "app" . "}",
                $this->apiClient->getSerializer()->toPathValue($app),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\RouteWrapper',
                '/apps/{app}/routes'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\RouteWrapper', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\RouteWrapper', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation appsAppRoutesRouteDelete
     *
     * Deletes the route
     *
     * @param string $app Name of app for this set of routes. (required)
     * @param string $route Route name (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return void
     */
    public function appsAppRoutesRouteDelete($app, $route)
    {
        list($response) = $this->appsAppRoutesRouteDeleteWithHttpInfo($app, $route);
        return $response;
    }

    /**
     * Operation appsAppRoutesRouteDeleteWithHttpInfo
     *
     * Deletes the route
     *
     * @param string $app Name of app for this set of routes. (required)
     * @param string $route Route name (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function appsAppRoutesRouteDeleteWithHttpInfo($app, $route)
    {
        // verify the required parameter 'app' is set
        if ($app === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app when calling appsAppRoutesRouteDelete');
        }
        // verify the required parameter 'route' is set
        if ($route === null) {
            throw new \InvalidArgumentException('Missing the required parameter $route when calling appsAppRoutesRouteDelete');
        }
        // parse inputs
        $resourcePath = "/apps/{app}/routes/{route}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($app !== null) {
            $resourcePath = str_replace(
                "{" . "app" . "}",
                $this->apiClient->getSerializer()->toPathValue($app),
                $resourcePath
            );
        }
        // path params
        if ($route !== null) {
            $resourcePath = str_replace(
                "{" . "route" . "}",
                $this->apiClient->getSerializer()->toPathValue($route),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/apps/{app}/routes/{route}'
            );

            return [null, $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation appsAppRoutesRouteGet
     *
     * Gets route by name
     *
     * @param string $app Name of app for this set of routes. (required)
     * @param string $route Route name (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\RouteWrapper
     */
    public function appsAppRoutesRouteGet($app, $route)
    {
        list($response) = $this->appsAppRoutesRouteGetWithHttpInfo($app, $route);
        return $response;
    }

    /**
     * Operation appsAppRoutesRouteGetWithHttpInfo
     *
     * Gets route by name
     *
     * @param string $app Name of app for this set of routes. (required)
     * @param string $route Route name (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\RouteWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function appsAppRoutesRouteGetWithHttpInfo($app, $route)
    {
        // verify the required parameter 'app' is set
        if ($app === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app when calling appsAppRoutesRouteGet');
        }
        // verify the required parameter 'route' is set
        if ($route === null) {
            throw new \InvalidArgumentException('Missing the required parameter $route when calling appsAppRoutesRouteGet');
        }
        // parse inputs
        $resourcePath = "/apps/{app}/routes/{route}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($app !== null) {
            $resourcePath = str_replace(
                "{" . "app" . "}",
                $this->apiClient->getSerializer()->toPathValue($app),
                $resourcePath
            );
        }
        // path params
        if ($route !== null) {
            $resourcePath = str_replace(
                "{" . "route" . "}",
                $this->apiClient->getSerializer()->toPathValue($route),
                $resourcePath
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\RouteWrapper',
                '/apps/{app}/routes/{route}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\RouteWrapper', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\RouteWrapper', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation appsAppRoutesRoutePatch
     *
     * Update a Route, Fails if the route or app does not exist. Accepts partial updates / skips validation of zero values.
     *
     * @param string $app name of the app. (required)
     * @param string $route route path. (required)
     * @param \Swagger\Client\Model\RouteWrapper $body One route to post. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\RouteWrapper
     */
    public function appsAppRoutesRoutePatch($app, $route, $body)
    {
        list($response) = $this->appsAppRoutesRoutePatchWithHttpInfo($app, $route, $body);
        return $response;
    }

    /**
     * Operation appsAppRoutesRoutePatchWithHttpInfo
     *
     * Update a Route, Fails if the route or app does not exist. Accepts partial updates / skips validation of zero values.
     *
     * @param string $app name of the app. (required)
     * @param string $route route path. (required)
     * @param \Swagger\Client\Model\RouteWrapper $body One route to post. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\RouteWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function appsAppRoutesRoutePatchWithHttpInfo($app, $route, $body)
    {
        // verify the required parameter 'app' is set
        if ($app === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app when calling appsAppRoutesRoutePatch');
        }
        // verify the required parameter 'route' is set
        if ($route === null) {
            throw new \InvalidArgumentException('Missing the required parameter $route when calling appsAppRoutesRoutePatch');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling appsAppRoutesRoutePatch');
        }
        // parse inputs
        $resourcePath = "/apps/{app}/routes/{route}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($app !== null) {
            $resourcePath = str_replace(
                "{" . "app" . "}",
                $this->apiClient->getSerializer()->toPathValue($app),
                $resourcePath
            );
        }
        // path params
        if ($route !== null) {
            $resourcePath = str_replace(
                "{" . "route" . "}",
                $this->apiClient->getSerializer()->toPathValue($route),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PATCH',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\RouteWrapper',
                '/apps/{app}/routes/{route}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\RouteWrapper', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\RouteWrapper', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation appsAppRoutesRoutePut
     *
     * Create a Route if it does not exist. Update if it does. Will also create app if it does not exist. Put does not skip validation of zero values
     *
     * @param string $app name of the app. (required)
     * @param string $route route path. (required)
     * @param \Swagger\Client\Model\RouteWrapper $body One route to post. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\RouteWrapper
     */
    public function appsAppRoutesRoutePut($app, $route, $body)
    {
        list($response) = $this->appsAppRoutesRoutePutWithHttpInfo($app, $route, $body);
        return $response;
    }

    /**
     * Operation appsAppRoutesRoutePutWithHttpInfo
     *
     * Create a Route if it does not exist. Update if it does. Will also create app if it does not exist. Put does not skip validation of zero values
     *
     * @param string $app name of the app. (required)
     * @param string $route route path. (required)
     * @param \Swagger\Client\Model\RouteWrapper $body One route to post. (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\RouteWrapper, HTTP status code, HTTP response headers (array of strings)
     */
    public function appsAppRoutesRoutePutWithHttpInfo($app, $route, $body)
    {
        // verify the required parameter 'app' is set
        if ($app === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app when calling appsAppRoutesRoutePut');
        }
        // verify the required parameter 'route' is set
        if ($route === null) {
            throw new \InvalidArgumentException('Missing the required parameter $route when calling appsAppRoutesRoutePut');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling appsAppRoutesRoutePut');
        }
        // parse inputs
        $resourcePath = "/apps/{app}/routes/{route}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($app !== null) {
            $resourcePath = str_replace(
                "{" . "app" . "}",
                $this->apiClient->getSerializer()->toPathValue($app),
                $resourcePath
            );
        }
        // path params
        if ($route !== null) {
            $resourcePath = str_replace(
                "{" . "route" . "}",
                $this->apiClient->getSerializer()->toPathValue($route),
                $resourcePath
            );
        }
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\RouteWrapper',
                '/apps/{app}/routes/{route}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\RouteWrapper', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\RouteWrapper', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
