<?php
/**
 * AppsWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fn
 *
 * The open source serverless platform.
 *
 * OpenAPI spec version: 0.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AppsWrapperTest Class Doc Comment
 *
 * @category    Class */
// * @description AppsWrapper
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AppsWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AppsWrapper"
     */
    public function testAppsWrapper()
    {
    }

    /**
     * Test attribute "next_cursor"
     */
    public function testPropertyNextCursor()
    {
    }

    /**
     * Test attribute "apps"
     */
    public function testPropertyApps()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }
}
